services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: lovedev_redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lovedev_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lovedev_api
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod

      # Database (use RDS connection)
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # File uploads
      FILE_UPLOAD_DIR: /app/uploads
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"
    mem_limit: 1g          # ← Correct syntax
    mem_reservation: 512m  # ← Correct syntax

    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - lovedev_network
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://api.lovedev.me/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: lovedev_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - lovedev_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  lovedev_network:
    driver: bridge
