# Development Environment Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovedev_db
    username: postgres
    password: sojeat
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    open-in-view: false  # Disable open-in-view

  flyway:
    enabled: true
    baseline-on-migrate: true
    #clean-disabled: false
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Application Configuration
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 900000 # 15 minutes
    refresh-expiration: 604800000 # 7 days

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:4200
      - http://localhost:5173
      - http://127.0.0.1:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  file:
    upload-dir: ./uploads
    max-size: 10485760 # 10MB
    allowed-extensions:

  email:
    from: noreply@lovedev.com
    from-name: LoveDev Team [DEV]
    verification-url: http://localhost:8081/api/v1/auth/verify-email
    reset-password-url: http://localhost:3000/reset-password

# Logging for Development
logging:
  level:
    root: INFO
    com.lovedev.api: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security.config.annotation.authentication.configuration: ERROR

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger{36} - %msg%n"

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

# Actuator for Development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          # Google OAuth2
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

          # GitHub OAuth2
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

          # Keycloak (if you want to use it)
          keycloak:
            client-id: lovedev-api
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/lovedev
            user-name-attribute: preferred_username