spring:
  application:
    name: lovedev_api

  profiles:
    active: prod  # Default profile

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Common config for all environments
app:
  name: LoveDev API
  version: 1.0.0

  pagination:
    default-page-size: 10
    max-page-size: 100

  file:
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - gif
      - webp

# Swagger (common settings)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080